'use client'
import { useCallback, useEffect, useState } from 'react'
import { Globe2, Megaphone, Search, Send, Users } from 'lucide-react'

const field='w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-sm outline-none focus:border-cyan-300/40'
export default function PlatformStudio(){
 const [data,setData]=useState<any>({inquiries:[],updates:[],translations:[],seo:{}});const [tab,setTab]=useState('hiring');const [notice,setNotice]=useState('');
 const load=useCallback(()=>fetch('/api/admin/platform').then(r=>r.json()).then(setData),[]);useEffect(()=>{load()},[load]);
 const save=async(payload:any)=>{setNotice('Saving…');const r=await fetch('/api/admin/platform',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const b=await r.json().catch(()=>({}));setNotice(r.ok?'Saved successfully.':b.error||'Save failed.');if(r.ok)load()}
 const tabs=[['hiring','Hiring funnel',Users],['updates','Now / updates',Megaphone],['languages','All languages',Globe2],['seo','SEO studio',Search]] as const
 return <div><header className="mb-8"><p className="font-mono text-[10px] uppercase tracking-[.28em] text-cyan-300">Portfolio Platform Studio</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Control the hiring experience</h1><p className="mt-2 text-sm text-white/40">Recruiter leads, public updates, unlimited BCP-47 locales, and search previews in one workspace.</p></header><div className="mb-6 flex flex-wrap gap-2">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`flex items-center gap-2 rounded-full border px-4 py-2 text-xs ${tab===id?'border-cyan-300/30 bg-cyan-300/10 text-cyan-100':'border-white/10 text-white/45'}`}><Icon size={14}/>{label}</button>)}</div>{notice&&<p className="mb-4 text-sm text-cyan-200">{notice}</p>}
 {tab==='hiring'&&<div className="grid gap-4">{data.inquiries.length===0?<Empty text="Qualified recruiter inquiries will appear here."/>:data.inquiries.map((x:any)=><article key={x.id} className="rounded-3xl border border-white/10 bg-white/[.025] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{x.name} <span className="font-normal text-white/35">· {x.company||'Independent'}</span></h2><a href={`mailto:${x.email}`} className="text-sm text-cyan-200">{x.email}</a></div><select value={x.status} onChange={e=>save({action:'inquiry_status',id:x.id,status:e.target.value})} className="rounded-lg border border-white/10 bg-black px-3 py-2 text-xs"><option>new</option><option>reviewing</option><option>contacted</option><option>closed</option></select></div><div className="mt-4 flex flex-wrap gap-2 text-[11px] text-white/40"><span>{x.role}</span><span>·</span><span>{x.opportunity_type}</span>{x.timeline&&<><span>·</span><span>{x.timeline}</span></>}</div><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-white/60">{x.message}</p></article>)}</div>}
 {tab==='updates'&&<UpdateEditor save={save} items={data.updates}/>} {tab==='languages'&&<LanguageEditor save={save} items={data.translations}/>} {tab==='seo'&&<SeoEditor save={save} seo={data.seo}/>}</div>
}
function Empty({text}:{text:string}){return <div className="rounded-3xl border border-dashed border-white/10 p-12 text-center text-sm text-white/35">{text}</div>}
function UpdateEditor({save,items}:{save:(x:any)=>void;items:any[]}){const [form,setForm]=useState<any>({title:'',summary:'',category:'build',link_url:'',published:true});return <div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><form onSubmit={e=>{e.preventDefault();save({action:'save_update',item:form});setForm({title:'',summary:'',category:'build',link_url:'',published:true})}} className="space-y-3 rounded-3xl border border-white/10 bg-white/[.025] p-5"><h2 className="text-lg font-semibold">Publish an update</h2><input className={field} placeholder="Update title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea className={field} rows={6} placeholder="What changed and why it matters" value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/><input className={field} placeholder="Category" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><input className={field} placeholder="Optional link" value={form.link_url} onChange={e=>setForm({...form,link_url:e.target.value})}/><label className="flex gap-2 text-sm text-white/55"><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/>Publish now</label><button className="flex w-full items-center justify-center gap-2 rounded-xl bg-white py-3 text-sm font-semibold text-black"><Send size={14}/>Add to /now</button></form><div className="space-y-3">{items.map(x=><article key={x.id} className="rounded-2xl border border-white/10 p-4"><p className="text-xs text-cyan-300">{x.category} · {x.published?'Published':'Draft'}</p><h3 className="mt-2 font-semibold">{x.title}</h3><p className="mt-2 text-sm text-white/45">{x.summary}</p></article>)}</div></div>}
function LanguageEditor({save,items}:{save:(x:any)=>void;items:any[]}){const [form,setForm]=useState<any>({locale:'',native_name:'',direction:'ltr',namespace:'common',translations:'{\n  "nav.home": "Home",\n  "nav.portfolio": "Portfolio",\n  "nav.contact": "Contact"\n}',enabled:true});return <div className="grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><form onSubmit={e=>{e.preventDefault();save({action:'save_translation',item:form})}} className="space-y-3 rounded-3xl border border-white/10 bg-white/[.025] p-5"><h2 className="text-lg font-semibold">Add any language</h2><p className="text-xs leading-5 text-white/40">Use any valid BCP-47 code: ar, hi, fil, pt-BR, zh-Hant, and every other language or regional variant.</p><div className="grid grid-cols-2 gap-3"><input className={field} placeholder="Locale code" value={form.locale} onChange={e=>setForm({...form,locale:e.target.value})}/><input className={field} placeholder="Native name" value={form.native_name} onChange={e=>setForm({...form,native_name:e.target.value})}/></div><select className={field} value={form.direction} onChange={e=>setForm({...form,direction:e.target.value})}><option className="bg-black" value="ltr">Left to right</option><option className="bg-black" value="rtl">Right to left</option></select><textarea className={`${field} font-mono`} rows={13} value={form.translations} onChange={e=>setForm({...form,translations:e.target.value})}/><button className="w-full rounded-xl bg-white py-3 text-sm font-semibold text-black">Save language bundle</button></form><div className="grid content-start gap-3 sm:grid-cols-2">{items.length?items.map(x=><div key={x.id} className="rounded-2xl border border-white/10 p-4"><p className="text-xl font-semibold">{x.native_name||x.locale}</p><p className="mt-1 font-mono text-xs text-cyan-300">{x.locale} · {x.direction} · {Object.keys(x.translations||{}).length} strings</p></div>):<Empty text="English fallback is active. Add any language here."/>}</div></div>}
function SeoEditor({save,seo}:{save:(x:any)=>void;seo:any}){const [f,setF]=useState<any>(null);useEffect(()=>{if(seo?.site_title)setF({...seo,keywords:(seo.keywords||[]).join(', ')})},[seo]);if(!f)return <Empty text="Loading SEO settings…"/>;return <div className="grid gap-6 xl:grid-cols-[1fr_.8fr]"><form onSubmit={e=>{e.preventDefault();save({action:'save_seo',item:f})}} className="space-y-3 rounded-3xl border border-white/10 bg-white/[.025] p-5"><input className={field} value={f.site_title||''} onChange={e=>setF({...f,site_title:e.target.value})}/><textarea className={field} rows={4} value={f.description||''} onChange={e=>setF({...f,description:e.target.value})}/><input className={field} placeholder="Keywords, comma separated" value={f.keywords||''} onChange={e=>setF({...f,keywords:e.target.value})}/><input className={field} placeholder="Open Graph image URL" value={f.og_image_url||''} onChange={e=>setF({...f,og_image_url:e.target.value})}/><input className={field} placeholder="Social title" value={f.social_title||''} onChange={e=>setF({...f,social_title:e.target.value})}/><textarea className={field} rows={3} placeholder="Social description" value={f.social_description||''} onChange={e=>setF({...f,social_description:e.target.value})}/><label className="flex gap-2 text-sm text-white/55"><input type="checkbox" checked={f.allow_indexing!==false} onChange={e=>setF({...f,allow_indexing:e.target.checked})}/>Allow search indexing</label><button className="w-full rounded-xl bg-white py-3 text-sm font-semibold text-black">Publish SEO settings</button></form><div><p className="mb-3 font-mono text-xs uppercase tracking-wider text-white/35">Share preview</p><div className="overflow-hidden rounded-2xl border border-white/15 bg-[#111]"><div className="aspect-[1.91/1] bg-gradient-to-br from-cyan-500/30 via-violet-500/20 to-black">{f.og_image_url&&<img src={f.og_image_url} alt="" className="h-full w-full object-cover"/>}</div><div className="p-4"><p className="text-xs text-white/30">sahad.is-a.dev</p><h3 className="mt-1 font-semibold">{f.social_title||f.site_title}</h3><p className="mt-2 line-clamp-2 text-sm text-white/45">{f.social_description||f.description}</p></div></div></div></div>}
