# .github/FUNDING.yml
# Supported funding model platforms

github: Dev-Sahad
patreon: DevSahad
open_collective: 
ko_fi: devsahad1
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
buy_me_a_coffee: devsahad1
thanks_dev: 
custom: ['https://sahad.is-a.dev']

