-- ========================================
-- EXTENSIONS
-- ========================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ========================================
-- TABLE: certificates
-- ========================================

CREATE TABLE public.certificates (
    id bigint NOT NULL,
    title text NOT NULL,
    image_url text,
    created_at timestamp without time zone DEFAULT now()
);

ALTER TABLE public.certificates
    ADD CONSTRAINT certificates_pkey PRIMARY KEY (id);

ALTER TABLE public.certificates
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- ========================================
-- TABLE: comments
-- ========================================

CREATE TABLE public.comments (
    id bigint NOT NULL,
    name text,
    comment text,
    image_url text,
    likes integer DEFAULT 0,
    is_pinned boolean DEFAULT false,
    replies jsonb DEFAULT '[]'::jsonb,
    created_at timestamp with time zone DEFAULT now(),
    liked_by_admin boolean DEFAULT false
);

ALTER TABLE public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);

ALTER TABLE public.comments
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- ========================================
-- TABLE: projects
-- ========================================

CREATE TABLE public.projects (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    title text NOT NULL,
    description text NOT NULL,
    live_url text,
    github_url text,
    technologies text[] DEFAULT '{}'::text[],
    key_features text[] DEFAULT '{}'::text[],
    image_url text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    image_urls jsonb DEFAULT '[]'::jsonb
);

ALTER TABLE public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);

-- ========================================
-- TABLE: tech_stack
-- ========================================

CREATE TABLE public.tech_stack (
    id bigint NOT NULL,
    name text NOT NULL,
    logo_url text,
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.tech_stack
    ADD CONSTRAINT tech_stack_pkey PRIMARY KEY (id);

ALTER TABLE public.tech_stack
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- ========================================
-- TABLE: site_settings
-- ========================================

CREATE TABLE public.site_settings (
    id integer DEFAULT 1 NOT NULL,
    owner_name text DEFAULT 'Muhammad Sahad',
    hero_title_primary text DEFAULT 'Frontend',
    hero_title_secondary text DEFAULT 'Developer',
    hero_role text DEFAULT 'Junior Programmer',
    hero_description text,
    availability_text text DEFAULT 'Available for work',
    about_eyebrow text DEFAULT 'ABOUT ME',
    about_title text DEFAULT 'Muhammad
Sahad',
    about_description text,
    about_quote text,
    cv_url text,
    github_url text,
    linkedin_url text,
    instagram_url text,
    youtube_url text,
    tiktok_url text,
    contact_heading text DEFAULT 'Contact Me',
    contact_subheading text,
    updated_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.site_settings
    ADD CONSTRAINT site_settings_pkey PRIMARY KEY (id);

-- ========================================
-- INDEXES
-- ========================================

CREATE INDEX idx_projects_created_at
ON public.projects(created_at);

CREATE INDEX idx_comments_created_at
ON public.comments(created_at);

-- ========================================
-- ROW LEVEL SECURITY
-- ========================================

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tech_stack ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

-- ========================================
-- POLICIES (OPEN PUBLIC ACCESS)
-- ========================================

CREATE POLICY "Allow public read projects"
ON public.projects
FOR SELECT
USING (true);

CREATE POLICY "Allow public insert comments"
ON public.comments
FOR INSERT
WITH CHECK (true);

CREATE POLICY "Allow public read comments"
ON public.comments
FOR SELECT
USING (true);

CREATE POLICY "Allow public read certificates"
ON public.certificates
FOR SELECT
USING (true);

CREATE POLICY "Allow public read tech_stack"
ON public.tech_stack
FOR SELECT
USING (true);

CREATE POLICY "Allow public read site_settings"
ON public.site_settings
FOR SELECT
USING (true);

CREATE POLICY "Allow authenticated manage site_settings"
ON public.site_settings
FOR ALL
USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');

-- ========================================
-- UPDATED_AT TRIGGER
-- ========================================

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_projects_updated_at
BEFORE UPDATE ON public.projects
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();
