import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowLeft, ArrowUpRight, BriefcaseBusiness, Gauge, Layers3 } from 'lucide-react'
import { createClient } from '@/utils/supabase/server'
import HiringInquiryForm from '@/components/HiringInquiryForm'

const profiles: Record<string,{eyebrow:string;title:string;intro:string;signals:string[]}>= {
  recruiter:{eyebrow:'Recruiter focus · 90 second scan',title:'A frontend engineer who ships polished, measurable products.',intro:'Fast evidence for hiring teams: selected work, technical range, case-study outcomes, and a direct qualified inquiry path.',signals:['Production Next.js and React','Design-to-code precision','Performance and accessibility ownership']},
  frontend:{eyebrow:'Engineering focus',title:'Interfaces built as systems, not screenshots.',intro:'Architecture, implementation decisions, responsive behavior, animation, integrations, and the trade-offs behind the output.',signals:['TypeScript + component systems','3D and motion with restraint','Supabase and server integrations']},
  founder:{eyebrow:'Founder focus',title:'From product idea to credible, launch-ready experience.',intro:'A concise view of business outcomes, product thinking, communication, and the ability to own a polished frontend delivery.',signals:['Fast product iteration','Clear scope and trade-offs','Conversion-aware UX']},
}

export function generateMetadata({params}:{params:Promise<{role:string}>}):Promise<Metadata>{return params.then(({role})=>{const p=profiles[role]||profiles.recruiter;return{title:`${p.title} · Hire Muhammad Sahad`,description:p.intro,alternates:{canonical:`/hire/${role}`},openGraph:{title:p.title,description:p.intro,url:`/hire/${role}`}}})}

export default async function HirePage({params}:{params:Promise<{role:string}>}){
  const {role}=await params;const profile=profiles[role]||profiles.recruiter;const db=await createClient();const {data:projects}=await db.from('projects').select('*').order('is_featured',{ascending:false}).order('featured_order').limit(3)
  return <main id="main-content" className="min-h-screen bg-[#070707] px-5 py-8 text-white sm:px-8 lg:px-14"><div className="mx-auto max-w-6xl"><header className="flex items-center justify-between"><Link href="/" className="flex items-center gap-2 text-sm text-white/50 hover:text-white"><ArrowLeft size={15}/>Portfolio</Link><nav className="flex gap-2">{Object.keys(profiles).map(x=><Link key={x} href={`/hire/${x}`} className={`rounded-full border px-3 py-1.5 text-xs capitalize ${x===role?'border-cyan-300/40 bg-cyan-300/10 text-cyan-100':'border-white/10 text-white/45'}`}>{x}</Link>)}</nav></header>
  <section className="grid min-h-[70vh] items-center gap-12 py-20 lg:grid-cols-[1.15fr_.85fr]"><div><p className="font-mono text-xs uppercase tracking-[.25em] text-cyan-300">{profile.eyebrow}</p><h1 className="mt-6 max-w-4xl text-5xl font-bold tracking-[-.05em] sm:text-7xl">{profile.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/55">{profile.intro}</p><div className="mt-8 grid gap-3 sm:grid-cols-3">{profile.signals.map((x,i)=>{const Icon=[Gauge,Layers3,BriefcaseBusiness][i];return <div key={x} className="rounded-2xl border border-white/10 bg-white/[.03] p-4"><Icon size={17} className="text-cyan-300"/><p className="mt-3 text-sm text-white/70">{x}</p></div>})}</div></div><HiringInquiryForm role={role}/></section>
  <section><div className="flex items-end justify-between"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-white/35">Selected proof</p><h2 className="mt-2 text-3xl font-semibold">Case studies worth opening</h2></div><Link href="/#portfolio" className="text-sm text-white/45">See all</Link></div><div className="mt-7 grid gap-5 md:grid-cols-3">{(projects||[]).map((p:any)=><article key={p.id} className="group rounded-3xl border border-white/10 bg-white/[.025] p-5"><div className="aspect-[16/10] overflow-hidden rounded-2xl bg-white/5">{p.image_url&&<img src={p.image_url} alt="" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/>}</div><h3 className="mt-5 text-xl font-semibold">{p.title}</h3><p className="mt-2 line-clamp-3 text-sm leading-6 text-white/45">{p.results||p.description}</p><div className="mt-5 flex gap-2"><Link href={`/portfolio/${p.id}`} className="flex items-center gap-1 text-sm text-cyan-200">Case study <ArrowUpRight size={14}/></Link>{p.live_url&&<Link href={`/demo/${p.id}`} className="ml-auto text-sm text-white/50">Demo room</Link>}</div></article>)}</div></section></div></main>
}
